= Alarms
:!toc-title:
:!toc-placement:
:toc:

Various modules to make CloudWatch Alarms easier to configure

toc::[]

== About

This is a collection of modules to help you set up CloudWatch Alarms!

The focus for this module is sensible defaults, and a low amount of configuration.

== Available Modules

These are the available modules in this repository.

link:./modules/api-gateway/[API Gateway]::
Monitor for discrepancies in your API Gateway hosted APIs.

link:./modules/lambda/[Lambda]::
Alarm for execution errors in your Lambda.

link:./modules/ecs-service/[ECS Service]::
Check for high CPU or memory usage in your services.

link:./modules/alb/[Application Load Balancer]::
See if something is wrong with services behind an ALB.

link:./modules/sqs-dlq/[SQS DLQ]::
Know when your SQS messages are ending up in a DLQ.

link:./modules/rds_overspent_instance_credits/[RDS Overspent Instance Credits]::
Monitor for RDS instances that have overspent their instance credits and incurred costs.

link:./modules/cloudwatch_log_level/[Cloudwatch Log Level]::
Monitor for too many logs with a specific log level in a service's cloudwatch logs.
  link:./modules/sns/[SNS]::
  Monitor SNS topics for no data.
